# Generated by Django 3.0.3 on 2020-02-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20200205_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trubadur_member',
            field=models.BooleanField(default=False),
        ),
    ]
