version: '3.8'

services:
  devcontainer:
    build: 
      context: frispel-docker
      dockerfile: Dockerfile
    volumes:
      - ./frispel-docker/database:/root/frispel/database
    ports:
      - 8000:8000
