version: '3.8'

services:
  web:
    restart: unless-stopped
    build: 
      context: frispel
      dockerfile: Dockerfile
    volumes:
      - ../site:/root/frispel/site
      - ../persistent/frispel/secrets:/root/frispel/secrets:ro
      - ../persistent/frispel/database:/root/frispel/database
      - ../log/frispel:/root/frispel/log
    ports:
      - 8000:8000
    networks:
      docker-network:
        aliases:
          - web

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=frispel.webmaster@gmail.com
    env_file:
      - ./nginx/nginx-docker.env
    ports:
      - 80:80
      - 443:443
    networks:
      docker-network:
        aliases:
          - nginx
    volumes:
      - ../persistent/nginx:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
      - ../log/nginx:/var/log/nginx

  gdrive:
    restart: unless-stopped
    build: 
      context: gdrive
      dockerfile: Dockerfile
    volumes:
      - ../persistent/frispel/database:/root/database
      - ../log/gdrive:/var/log/gdrive
    ports:
      - 8085:8085

networks:
  docker-network:
    driver: bridge
