# Generated by Django 3.0.1 on 2019-12-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ltuId',
            new_name='ltu_id',
        ),
    ]
