# Generated by Django 3.0.1 on 2019-12-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20191227_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership_status',
            field=models.BooleanField(default=False),
        ),
    ]
