# Generated by Django 3.0.1 on 2019-12-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_userprofile_membership_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='membership_status',
            new_name='extended_membership_status',
        ),
    ]
