# Generated by Django 3.0.1 on 2019-12-27 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20191227_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
