# Generated by Django 3.1.14 on 2023-01-31 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_rename_expiry_date_userprofile_application_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ltu_id',
        ),
    ]
