# Generated by Django 3.0.1 on 2019-12-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20191222_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
