# Generated by Django 3.2.7 on 2021-09-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='access_applied',
            field=models.BooleanField(default=True),
        ),
    ]
