# Generated by Django 3.2.7 on 2021-09-21 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_userprofile_access_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='access_applied',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registered_expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
