# Generated by Django 3.1.14 on 2023-01-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_remove_userprofile_ltu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_set_up',
            field=models.BooleanField(default=False),
        ),
    ]
